### PR TITLE
fix: break graph api notifiers across a sync map

### PR DESCRIPTION
**Pull request by willscott**
Limits how many other exchanges / notifiers are notified.

Aims to fix https://github.com/ipfs/bifrost-gateway/issues/92

### CODE REVIEW

**Comment by lidel** [comment]
Due to https://github.com/protocol/bifrost-infra/pull/2492 we had to restart  the experiment:

```
2023/04/25 20:14:30 Starting bifrost-gateway 2023-04-25-8e1661e
```

**Comment by aarshkshah1992** [comment]
@lidel Which file should I change if I want to change some environment/config variables for Bifrost ?
When will they get overwritten by CI ?

**Comment by willscott** [comment]
@aarshkshah1992  https://github.com/protocol/bifrost-infra/blob/master/ansible/inventories/bifrost-gw/group_vars/gateway_bifrost_stage.yml#L43 is probably what you're after?

**Comment by lidel** [comment]
@aarshkshah1992  `/data/update-bifrost.sh`  sets values ad-hoc, if you want to keep them around across automated restarts, you need to use file linked by @willscott

**Review by lidel — APPROVED** [review]
I think this PR did remove the perf. erosion over  ~2h time window described in https://github.com/ipfs/bifrost-gateway/issues/92.

We had a pretty long window running https://github.com/ipfs/bifrost-gateway/pull/102/commits/8e1661e018bc201b6a8a54186c10444e524b64af, and it maintained correctness over time:

>  

Let's merge this, so we move focus to the next dragon.

**Pull request merged**
