### PR TITLE
refactor: use IPIP-402 param names when GRAPH_BACKEND=true

### PR DESCRIPTION
**Pull request by lidel**
Ref. https://github.com/ipfs/specs/pull/402

This PR follows a transition plan from #80  to send all versions until every system (lassie, l1) upgrades.

### CODE REVIEW

**Comment by lidel** [comment]
I'd like to ship this to staging, and if no issues, tag a release and ship to prod as well, to unblock other systems and allow them to safely switch to new names.

@aarshkshah1992 Depending on how HTTP cache key is built on L1 and nginx, this may temporarily produce high % of cache misses, impact latency etc. Due to this want to get :+1:  from you  before shipping this, in case you have any experiment running on staging.

**Comment by willscott** [comment]
@aarshkshah1992  is okay with this happening - ping him on slack before you deploy to staging

**Comment by aarshkshah1992** [comment]
@lidel _"Depending on how HTTP cache key is built on L1 and nginx, this may temporarily produce high % of cache misses, impact latency etc."_

Could you elaborate more on this. Do we have a mitigation plan in place if this does indeed happen i.e. how do we then improve the latency, cache hit percentage etc ? Will we have to roll back the change or do some work on Saturn ?

**Comment by lidel** [comment]
We  need to wait for cache to fill up with the new URLs, and things will get back to normal.

**Review by hacdias — COMMENTED** [review]
Just to see if I understand what's happening here: we're adding support for IPIP-0402 parameters on the parameters we pass to the backend, right? The gateway itself does not support them but will after we have https://github.com/ipfs/boxo/pull/303. If that is the case, I would rename the PR.

**Pull request merged**
